---

# Author: Tony Fahrion <tony.fahrion@de.clara.net>

# dependencies:
#   internal: de-docker-images/spryker-base
#   external docker hub: dind

# this .gitlab-ci.yml file requires that the gitlab-runner is started with DOCKER_PRIVILEGED=yes!
# this is because of the docker-in-docker image build


stages:
  - build
  - test
  - release

# checkout: http://docs.gitlab.com/ce/ci/variables/README.html
variables:
  CONTAINER_SPRYKER_BASE:  $CI_REGISTRY/de-docker-images/spryker-base:latest
  CONTAINER_RELEASE_IMAGE_PHP56: $CI_REGISTRY/$CI_PROJECT_PATH:latest_php56
  CONTAINER_TEST_IMAGE_PHP56:    $CI_REGISTRY/$CI_PROJECT_PATH:${CI_BUILD_REF}_php56
  CONTAINER_RELEASE_IMAGE_PHP70: $CI_REGISTRY/$CI_PROJECT_PATH:latest_php70
  CONTAINER_TEST_IMAGE_PHP70:    $CI_REGISTRY/$CI_PROJECT_PATH:${CI_BUILD_REF}_php70
  ZED_DB_USERNAME:         spryker
  ZED_DB_PASSWORD:         test123
  ZED_DB_DATABASE:         spryker
  POSTGRES_USER:           spryker
  POSTGRES_PASSWORD:       test123
  POSTGRES_DB:             spryker
  JENKINS_HOST:            jenkins
  JENKINS_PORT:            "8080"
  YVES_HOST:               $CI_SERVER_NAME


# login to private gitlab registry
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

# ==========================
#      Job templates
# ==========================
# special gitlab yaml feature, see: https://docs.gitlab.com/ce/ci/yaml/README.html#anchors

.build_demoshop_template: &build_demoshop_definition
  stage: build
  image: docker:git
  script:
    - export SED_COMMAND_ARG=$CONTAINER_SPRYKER_BASE_PHP
    - sed -i "s#spryker-base:latest#${SED_COMMAND_ARG}#g" Dockerfile # replace "FROM ..." statement
    - docker build -t $REGISTRY_IMAGE_NAME . \
                  --build-arg PHP_VERSION=$PHP_VERSION \
                  --build-arg NODEJS_VERSION=$NODEJS_VERSION \
                  --build-arg NODEJS_PACKAGE_MANAGER=$NODEJS_PACKAGE_MANAGER
    - docker push $REGISTRY_IMAGE_NAME
  services:
    - docker:dind
  only:
    - feature/clara-dockerize
    - feature/clara-enable_gitlabci_tests


# ==========================
#      Job definitions
# ==========================


# STAGE: build
build_demoshop_php56:
  <<: *build_demoshop_definition
  variables:
    PHP_VERSION: "5.6"
    NODEJS_VERSION: "6"
    NODEJS_PACKAGE_MANAGER: "npm"
    REGISTRY_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:php5.6_latest

build_demoshop_php70:
  <<: *build_demoshop_definition
  variables:
    PHP_VERSION: "7.0"
    NODEJS_VERSION: "6"
    NODEJS_PACKAGE_MANAGER: "npm"
    REGISTRY_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:php7.0_latest



# fetch docker image (spryker demoshop)
# init container (run entrypoint.sh init_setup)
#test_init_setup:
#  stage: test
#  image: $CONTAINER_TEST_IMAGE
##  image: docker:git
#  script:
#    - /entrypoint.sh init_setup
##    - docker run registry.eu.clara.net/$CI_PROJECT_PATH:8b2e28c3ba420b369d0843a561287f019a0b3cf7 "ping elasticsearch; /entrypoint.sh init_setup"
#  services:
##    - docker:dind
#    - redis:latest
#    - postgres:9.4.10
#    - jenkins:latest
#    - elasticsearch:2
