build:
    environment:
        php: '7.1'
    dependencies:
        before:
            - 'composer remove --dev spryker/git-hook'

    tests:
        override:
            - true # disable test execution on scrutinizer
