--- 

version: '2'
services: 

  static-assets:
    image: "busybox:latest"
    command: /bin/true
    restart: never
    volumes:
      - /data/shop/public/Yves/assets
      - /data/shop/public/Zed/assets

  yves-and-zed: 
    image: "spryker-demo-shop:latest"
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2380:80"
      - "2381:8080"
    links:
      - redis
      - elasticsearch
      - "postgres:database"
    env_file: ./docker-compose.env
    volumes:
      - ./assets:/data/shop/assets
    volumes_from:
      - static-assets:ro

  init:
    image: "spryker-demo-shop:latest"
    command: "init_setup"
    restart: never
    depends_on:
      - yves-and-zed
    env_file: ./docker-compose.env
    volumes:
      - ./assets:/data/shop/assets
    volumes_from:
      - static-assets:rw

  redis:
    image: "redis"
    restart: always

  elasticsearch:
    image: "elasticsearch:2"
    restart: always

  postgres:
    image: "postgres"
    restart: always
    env_file: ./docker-compose.env
