--- 

version: '2'
services: 

  shared-assets:
    image: "busybox:latest"
    command: /bin/true
    restart: never
    volumes:
      - /data/shop/public/Yves/assets
      - /data/shop/public/Zed/assets
      - /data/shop/src/Generated

  yves-and-zed: 
    image: "spryker-demo-shop:latest"
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "2380:80"
      - "2381:8080"
    links:
      - redis
      - elasticsearch
      - database
    env_file: ./docker-compose.env
    volumes_from:
      - shared-assets:rw

  init:
    image: "spryker-demo-shop:latest"
    command: "init_setup"
    #command: sleep 1d
    restart: never
    privileged: true
    depends_on:
      - yves-and-zed
    links:
      - redis
      - elasticsearch
      - database
    env_file: ./docker-compose.env
    volumes:
      - ../assets:/data/shop/assets
    volumes_from:
      - shared-assets:rw

  redis:
    image: "redis"
    restart: always

  elasticsearch:
    image: "elasticsearch:2"
    restart: always

  database:
    image: "postgres"
    restart: always
    env_file: ./docker-compose.env

  jenkins:
    image: "jenkins"
    ports: 
      - "10007:8080"
    env_file: ./docker-compose.env
    volumes:
      - /var/jenkins_home jenkins
