---

version: '3.4'

x-service_config: &x-service_config
  image: "${IMAGE}:${VERSION}"
  restart: always
  volumes: ${VOLUMES}

x-zed_environment: &zed_environment
  - APPLICATION_ENV
  - ZED_SESSION_REDIS_PASSWORD
  - STORAGE_REDIS_PASSWORD
  - ZED_DATABASE_PASSWORD
  - RABBITMQ_PASSWORD
  - DOCUMENT_ROOT=/app/public/Zed
  - PHPFPM_HOST=zed-phpfpm

x-yves_environment: &yves_environment
  - APPLICATION_ENV
  - YVES_SESSION_REDIS_PASSWORD
  - STORAGE_REDIS_PASSWORD
  - DOCUMENT_ROOT=/app/public/Yves
  - PHPFPM_HOST=yves-phpfpm

services:
  init:
    <<: *x-service_config
    command:
      - start
      - init
    restart: "no"
    environment: *zed_environment

  yves-nginx:
    <<: *x-service_config
    command:
      - start
      - nginx
    ports:
      - "20100:80"
    environment: *yves_environment

  yves-phpfpm:
    <<: *x-service_config
    command:
      - start
      - phpfpm
    environment: *yves_environment

  zed-nginx:
    <<: *x-service_config
    command:
      - start
      - nginx
    ports:
      - "20200:80"
    environment: *zed_environment

  zed-phpfpm:
    <<: *x-service_config
    command:
      - start
      - phpfpm
    environment: *zed_environment

  yves-session-redis:
    image: "redis:4.0.9-alpine"
    command: >
      --requirepass $YVES_SESSION_REDIS_PASSWORD
      --appendonly yes
    volumes:
      - /data

  zed-session-redis:
    image: "redis:4.0.9-alpine"
    command: >
      --requirepass $ZED_SESSION_REDIS_PASSWORD
      --appendonly yes
    volumes:
      - /data

  storage-redis:
    image: "redis:4.0.9-alpine"
    command: >
      --requirepass $STORAGE_REDIS_PASSWORD
      --appendonly yes
    volumes:
      - /data

  elasticsearch:
    image: "elasticsearch:2.4-alpine"
    ports:
      - "20500:9200"
    volumes:
      - /usr/share/elasticsearch/data

  database:
    image: "postgres:9.6.9-alpine"
    ports:
      - "20600:5432"
    environment:
      POSTGRES_PASSWORD: "$ZED_DATABASE_PASSWORD"
      POSTGRES_USER: "spryker"
      POSTGRES_DB: "spryker"
    volumes:
      - /var/lib/postgresql/data

  jenkins:
    image: "jenkins/jenkins:lts-alpine"
    ports:
      - "20300:8080"
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      JENKINS_OPTS: "-remoting"
    volumes:
      - /var/jenkins_home

  jenkins-slave:
    <<: *x-service_config
    image: "${IMAGE}:${VERSION}-jenkins"
    command:
      - start
      - jenkins-slave
    environment: *zed_environment
