--- 

version: '3'

services: 
  zed: 
    image: "spryker-demoshop:latest"
    command: "run_zed"
    #command: "sleep 1d"
    #restart: always
    restart: "no"
    depends_on:
      - database
      - redis
      - elasticsearch
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "2381:80"
    links:
      - redis
      - elasticsearch
      - database
    env_file: ./docker-compose.env

  yves: 
    image: "spryker-demoshop:latest"
    command: "run_yves"
    #command: "sleep 1d"
    #restart: always
    restart: "no"
    depends_on:
      - zed
    ports:
      - "2380:80"
    links:
      - zed
      - redis
      - elasticsearch
    env_file: ./docker-compose.env

  redis:
    image: "redis:3.2-alpine"
    restart: always

  elasticsearch:
    # TODO: images is deprecated and maintained until the 2017-06-20
    # see https://hub.docker.com/_/elasticsearch/
    image: "elasticsearch:2.4-alpine"
    restart: always
    # just to create a simple delay for init phase
    depends_on:
      - database

  database:
    image: "postgres:9.4.11-alpine"
    restart: always
    env_file: ./docker-compose.env

  jenkins:
    image: "jenkins:alpine"
    ports: 
      - "10007:8080"
    env_file: ./docker-compose.env
